### ISSUE TITLE
Support configuration cache

### ISSUE THREAD

**Issue by Nightenom** [zaproxy/gradle-plugin-crowdin#28]
Hi, we're getting following error when trying to run our project with `--configuration-cache`
```
Task `:crowdinUploadSourceFiles` of type `org.zaproxy.gradle.crowdin.tasks.UploadSourceFiles`: invocation of 'Task.project' at execution time is unsupported.
```

**Comment by Thodor12** [comment]
Added information, the one line we were able to find is: <https://github.com/zaproxy/gradle-plugin-crowdin/blob/main/src/main/java/org/zaproxy/gradle/crowdin/tasks/CrowdinTask.java#L121>, because this uses `getProject()`

**Comment by psiinon** [comment]
What are you trying to do?
This is an internal ZAP tool which we dont expect other people or projects to use...

**Comment by kingthorin** [comment]
Mmmm I thought the crowdin plugin was meant to be generic? 🤷‍♂️ If others can use it without or with only minimal changes that's fine I think.

**Comment by Thodor12** [comment]
We're using it for our own project and it's working just fine, however we're trying to enable the configuration cache that Gradle introduced.
The configuration cache requires that all usages of build-time information be used only during build time and not during runtime.
So in this case, a usage of `getProject()` will cause the configuration cache to fail.

I was trying to see if I could fix it myself and make a PR, but so far no dice yet.

**Comment by Thodor12** [comment]
I managed to fix the issue, I see you were already on the track to 0.5.0, if not too much of an inconvenience is it possible to release a 0.4.1 or will we have to wait for 0.5.0?
In case of the latter, what is the estimated timeframe to the next release?
